### ISSUE TITLE
ParEGO: inconsistent of number of weigh vectors between the code and ParEGO paper

### ISSUE THREAD

**Issue by Youwei-He** [zhandawei/Bayesian_Optimization_Algorithms#1]
the number of weigh vectors between the code and ParEGO paper is inconsistent for three-objective, i.e. 15 in the code, while it is combinatorial number of (s+k-1) over (k-1) described in paper. the k is the number of objective, s denotes the parameters determining the number of weigh vectors. For three-objective applications, the number of weigh vectors should be much greater than 15.

I guess the users  might not notice such difference. Therefore, it would be nice to correct this.

**Comment by zhandawei** [comment]
The setting is given in Table V in this paper, where the number of scalarizing vectores is 11 for k=2 and 15 for k=3. The reason of using a small number of vectors is explained by the author as "we chose a number which would allow several passes over each scalarizing vector". If using a large number of vectors, each vector will be covered in fewer times.

**Comment by zhandawei** [comment]
Also can be seen from the author's implementation https://github.com/CristinaCristescu/ParEGO_Eigen/blob/master/ParEGO.zip

    if(fobjectives==2){
        N=10;  // gives 11 weight vectors  - of objectives
        wvSize = pow(11, fobjectives);
        wv.resize(wvSize, std::vector<int>(MAX_K));
    }
    else if(fobjectives==3)
    {
        N=4;  // gives 15 weight vectors
        wvSize = pow(15, fobjectives);
        wv.resize(wvSize, std::vector<int>(MAX_K));

    }
    else if(fobjectives==4)
    {
        N=3;   // gives 20 weight vectors
        wvSize = pow(20, fobjectives);
        wv.resize(wvSize, std::vector<int>(MAX_K));
    }

    snake_wv();
}
